import{r as s}from"./lit-element.js";import{x as i}from"./if-defined.js";import{p as h,c as a}from"./core.js";class l extends h(s){static get properties(){return{viewerWidth:{type:Number,attribute:!1},viewerHeight:{type:Number,attribute:!1},viewerScaleX:{type:Number,attribute:!1},viewerScaleY:{type:Number,attribute:!1},viewerContWidth:{type:Number,attribute:"viewer-cont-width"},viewerContHeight:{type:Number,attribute:"viewer-cont-height"},visiblePages:{type:Number,attribute:"pages"}}}constructor(){var t,e;super(),this.customClass=this.getAttribute("customClass"),this.defaultClass=this.getAttribute("defaultClass")||"viewer",this.typeClass=this.hasAttribute("type")?"wrap-"+this.getAttribute("type"):this.getAttribute("type")||"wrap",this.viewerWidth=this.getBoundingClientRect().width,this.viewerHeight=this.getBoundingClientRect().height,this.viewerContWidth=this.getAttribute("viewer-cont-width")||parseFloat((t=getComputedStyle(document.documentElement).getPropertyValue("--view-cont-w"))==null?void 0:t.trim())||null,this.viewerContHeight=this.getAttribute("viewer-cont-height")||parseFloat((e=getComputedStyle(document.documentElement).getPropertyValue("--view-cont-h"))==null?void 0:e.trim())||null,this.visiblePages=this.getAttribute("visible-pages")||2,this.viewerScaleX=this.viewerWidth/this.viewerContWidth,this.viewerScaleY=this.viewerHeight/this.viewerContHeight,this.debugComponentMessage={"뷰어 스케일(X)":{key:"viewerScaleX",value:this.viewerScaleX},"뷰어 스케일(Y)":{key:"viewerScaleY",value:this.viewerScaleY},"뷰어 넓이":{key:"viewerWidth",value:this.viewerWidth},"뷰어 높이":{key:"viewerHeight",value:this.viewerHeight},"컨텐츠 넓이":{key:"viewerContWidth",value:this.viewerContWidth},"컨텐츠 높이":{key:"viewerContHeight",value:this.viewerContHeight},"보여질 페이지 수":{key:"visiblePages",value:this.visiblePages}}}firstUpdated(){this.renderStatic()}viewerScale(){}renderStatic(){Array.from(this.querySelectorAll(":scope > ig-item")).forEach((e,r)=>{this.data[r]={src:e.hasAttribute("src")?e.getAttribute("src"):null,cont:e.hasAttribute("src")?null:e.children},e.remove()})}render(){return this.data.length?i`
				<div class="${this.defaultClass}-zoom">
					<div class="${this.defaultClass}-cont" style="width:${this.viewerContWidth*this.visiblePages+"px"}; height:${this.viewerContHeight+"px"} transform:translate(-50%, -50%) scale(${Math.min(this.viewerScaleX,this.viewerScaleY)});">
						<div class="${this.defaultClass}-page">
							${this.data.map((t,e)=>t.src?i`<iframe src="${t.src}" style="width:${this.viewerContWidth+"px"}; height:${this.viewerContHeight+"px"}"></iframe>`:i`<div style="width:${this.viewerContWidth+"px"}; height:${this.viewerContHeight+"px"}">${t.cont}</div>`)}
						</div>
					</div>
				</div>
			`:i`${this.renderNoData()}`}}customElements.define(`${a}viewer`,l);
