import{r as o}from"./lit-element.js";import{x as e}from"./if-defined.js";import{p as g,c}from"./core.js";class p extends g(o){static get properties(){return{move:{type:Boolean,reflect:!0},src:{type:String,reflect:!0},imageSize:{type:Object,attribute:!1},wrapSize:{type:Object,attribute:!1},imageEl:{type:Object,attribute:!1},wrapEl:{type:Object,attribute:!1}}}constructor(){super(),this.customClass=this.getAttribute("customClass"),this.defaultClass=this.getAttribute("defaultClass")||"thumb",this.typeClass="type",this.imageSize={width:0,height:0},this.move=this.hasAttribute("move"),this.src=this.getAttribute("src")||" ",this.wrapSize={width:0,height:0},this.debugComponentMessage={"이미지 주소":{key:"src",value:this.src},이미지:{key:"imageEl",value:this.imageEl},"이미지 크기":{key:"imageSize",value:[this.imageSize.width,this.imageSize.height]},타입:{key:"type",value:this.type},컨테이너:{key:"wrapEl",value:this.wrapEl},"컨테이너 크기":{key:"wrapSize",value:[this.wrapSize.width,this.wrapSize.height]}}}firstUpdated(){this.renderStatic()}updateWrapSize(){this.wrapEl&&(this.wrapSize={width:this.wrapEl.clientWidth,height:this.wrapEl.clientHeight})}handleImage(t){if(!this.move)return;const{offsetX:i,offsetY:l}=t,{width:h,height:r}=this.imageSize,{width:s,height:a}=this.wrapSize,m=i/s*(h-s)-(h-s)/2,d=l/a*(r-a)-(r-a)/2;(h>s||r>a)&&(this.imageEl.style.transform=`translate(${m}px, ${d}px)`)}handleImageLoad(t){this.imageEl=t.target,this.imageSize={width:this.imageEl.naturalWidth,height:this.imageEl.naturalHeight},this.updateComplete.then(()=>{this.updateWrapSize()})}handleImageReset(){this.imageEl.style.transform=""}renderStatic(){var t,i;this.data={src:((t=this.querySelector(":scope > img"))==null?void 0:t.getAttribute("src"))||this.src,leftTop:this.customElementReplace("ig-lt"),rightTop:this.customElementReplace("ig-rt"),leftBottom:this.customElementReplace("ig-lb"),rightBottom:this.customElementReplace("ig-rb"),center:this.customElementReplace("ig-c")},(i=this.querySelector(":scope > img"))==null||i.remove(),this.wrapEl=this.querySelector(`.${this.defaultClass}-inner`)}render(){return e`
			<div
				class="${this.defaultClass}-inner${this.type?` ${this.defaultClass+"-"+this.type}`:""}"
				@mousemove="${this.move?this.handleImage:void 0}"
				@mouseout="${this.move?this.handleImageReset:void 0}"
			>
				<img src="${this.data.src}" onerror="this.remove ? this.remove() : this.removeNode();" style="${this.type==="center"?this.imageSize.width>this.imageSize.height?"width:100%;":"height:100%;":""}" @load="${this.handleImageLoad}">
				${this.data.leftTop?e`<div class="${this.defaultClass}-lt">${this.data.leftTop}</div>`:""}
				${this.data.rightTop?e`<div class="${this.defaultClass}-rt">${this.data.rightTop}</div>`:""}
				${this.data.leftBottom?e`<div class="${this.defaultClass}-lb">${this.data.leftBottom}</div>`:""}
				${this.data.rightBottom?e`<div class="${this.defaultClass}-rb">${this.data.rightBottom}</div>`:""}
				${this.data.center?e`<div class="${this.defaultClass}-c">${this.data.center}</div>`:""}
			</div>
		`}}customElements.define(`${c}thumb`,p);
